version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: config_postgres
    restart: always
    environment:
      POSTGRES_DB: ConfigurationDb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro


  webui:
    build:
      context: .
      dockerfile: ConfigurationUI/Dockerfile
    container_name: config_webui
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=ConfigurationDb;Username=admin;Password=admin123
    depends_on:
      - postgres

volumes:
  pgdata:
  